#!/bin/bash -e
#
# ===----------------------------------------------------------------------===
#
#  Swift Android SDK: Docker Container Build Script
#
#  This source file is part of the Swift.org open source project
#
#  Copyright (c) 2025 Apple Inc. and the Swift project authors
#  Licensed under Apache License v2.0 with Runtime Library Exception
#
#  See https://swift.org/LICENSE.txt for license information
#  See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
#
# ===----------------------------------------------------------------------===

# default architectures to build for
TARGET_ARCHS=${TARGET_ARCHS:-aarch64,x86_64,armv7}

ANDROID_NDK_VERSION=android-ndk-r27d

BASEPATH=$(dirname $(realpath $0))
cd ${BASEPATH}

export SWIFT_VERSION=${1}
# note that WORKDIR must not be under the current checkout or the patches will fail to apply
WORKDIR=${2}
if [[ "${WORKDIR}" == '' ]]; then
    echo "Usage: $(basename $0) <release/devel/trunk> <work directory>"
    exit 1
fi
mkdir -p ${WORKDIR}
WORKDIR=$(realpath ${WORKDIR})

HOST_OS=ubuntu24.04
source ./scripts/toolchain-vars.sh

# Check-out and patch the sources
./scripts/fetch-source.sh --source-dir ${WORKDIR}/source

mkdir -p ${WORKDIR}/products
chmod ugo+rwx ${WORKDIR}/products

if [[ "$DOCKER" == "" ]]; then
    DOCKER=docker
fi

CONTAINER_NAME="swift-android"

# Build the Docker image
$DOCKER build --build-arg OS_ARCH_SUFFIX=$OS_ARCH_SUFFIX --build-arg SWIFT_TOOLCHAIN_URL=$SWIFT_TOOLCHAIN_URL --build-arg ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION -t ${CONTAINER_NAME} .

$DOCKER run -i --rm \
          -v ${WORKDIR}/source:/source \
          -v ${WORKDIR}/products:/products:rw \
          ${CONTAINER_NAME} \
          /scripts/build.sh \
            --source-dir "/source" \
            --products-dir "/products" \
            --host-toolchain "/usr/local/swift" \
            --build-compiler "${BUILD_COMPILER}" \
            --ndk-home "/usr/local/ndk/${ANDROID_NDK_VERSION}" \
            --archs "${TARGET_ARCHS}"
