#!/bin/bash -e
#
# ===----------------------------------------------------------------------===
#
#  Swift Android SDK: Docker Container Build Script
#
#  This source file is part of the Swift.org open source project
#
#  Copyright (c) 2025 Apple Inc. and the Swift project authors
#  Licensed under Apache License v2.0 with Runtime Library Exception
#
#  See https://swift.org/LICENSE.txt for license information
#  See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
#
# ===----------------------------------------------------------------------===

# default architectures to build for
TARGET_ARCHS=${TARGET_ARCHS:-aarch64,x86_64,armv7}

ANDROID_NDK_VERSION=android-ndk-r27d
ANDROID_API=28

BASEPATH=$(dirname $(realpath $0))
cd ${BASEPATH}

SKIP_FETCH=false
while [ "$#" -gt 0 ]; do
    case "$1" in
        --skip-fetch) SKIP_FETCH=true ;;
        *) break ;;
    esac
    shift
done

export SWIFT_VERSION=${1}
# note that WORKDIR must not be under the current checkout or the patches will fail to apply
WORKDIR=${2}
if [[ "${WORKDIR}" == '' ]]; then
    echo "Usage: $(basename $0) <release/devel/trunk> <work directory>"
    exit 1
fi
mkdir -p ${WORKDIR}
WORKDIR=$(realpath ${WORKDIR})

HOST_OS=ubuntu24.04
source ./scripts/toolchain-vars.sh

# Check-out and patch the sources
if [[ "$SKIP_FETCH" != "true" ]]; then
    ./scripts/fetch-source.sh --source-dir ${WORKDIR}/source
fi

# Work around swiftlang/swift-driver#1822 for now
perl -0777 -pi -e "s#(call rm ... \".\{LIBDISPATCH_BUILD_DIR\}\"\n(\s+)fi\n)#\1\2if [[ -d \"\\\${ANDROID_NDK}\" ]]; then call ln -sf \"\\\${SWIFT_BUILD_PATH}/lib/swift\" \"\\\${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib\"; fi#g" ${WORKDIR}/source/swift-project/swift/utils/build-script-impl

# Push trunk back to build against Android API 24 with NDK 28c
if [[ -n "${SWIFT_VERSION}" && ($SWIFT_VERSION != scheme:release/6.3 && $SWIFT_VERSION != tag:swift-6.3-*) ]]; then
    ANDROID_NDK_VERSION=android-ndk-r28c
    ANDROID_API=23
fi

mkdir -p ${WORKDIR}/products
chmod ugo+rwx ${WORKDIR}/products

if [[ "$DOCKER" == "" ]]; then
    DOCKER=docker
fi

CONTAINER_NAME="swift-android"

# Build the Docker image
$DOCKER build --build-arg OS_ARCH_SUFFIX=$OS_ARCH_SUFFIX --build-arg SWIFT_TOOLCHAIN_URL=$SWIFT_TOOLCHAIN_URL --build-arg ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION --build-arg http_proxy --build-arg https_proxy --build-arg HTTP_PROXY --build-arg HTTPS_PROXY -t ${CONTAINER_NAME} .

$DOCKER run -i --rm \
          -e http_proxy -e https_proxy \
          -e HTTP_PROXY -e HTTPS_PROXY \
          -v ${WORKDIR}/source:/source \
          -v ${WORKDIR}/products:/products:rw \
          ${CONTAINER_NAME} \
          /scripts/build.sh \
            --source-dir "/source" \
            --products-dir "/products" \
            --host-toolchain "/usr/local/swift" \
            --build-compiler "${BUILD_COMPILER}" \
            --android-api "${ANDROID_API}" \
            --ndk-home "/usr/local/ndk/${ANDROID_NDK_VERSION}" \
            --archs "${TARGET_ARCHS}"
